name: Bry Antonio
favicon: null
layout_spectrum: 1
typography_spectrum: 0.37097
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f1f1f'
    - '#4c503f'
    - '#707054'
    - '#e3dea1'
    - '#8b8963'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
